on:
  workflow_dispatch:
  push:
    branches:
      - main

name: Delpoy to Google Cloud Run
env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.0
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true  # Set to true to authenticate the Cloud Run action

      - name: Authorize Docker Push
        run: gcloud auth configure-docker

      - name: Build Server Container
        run: docker build -t gcr.io/${{ env.PROJECT_ID }}/server:${{  github.sha }} server

      - name: Build Client Container
        run: docker build -t gcr.io/${{ env.PROJECT_ID }}/client:${{  github.sha }} client

      - name: Push Server Container
        run: docker push gcr.io/${{ env.PROJECT_ID }}/server:${{  github.sha }}

      - name: Push Client Container
        run: docker push gcr.io/${{ env.PROJECT_ID }}/client:${{  github.sha }}

      - name: Deploy Server
        id: deploy_server
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: server
          image: gcr.io/${{ env.PROJECT_ID }}/server:${{  github.sha }}

      - name: Show Server Output
        run: echo ${{ steps.deploy_server.outputs.url }}

      - name: Deploy Client
        id: deploy_client
        uses: google-github-actions/deploy-cloudrun@v0.4.0
        with:
          service: client
          image: gcr.io/${{ env.PROJECT_ID }}/client:${{  github.sha }}

      - name: Show Client Output
        run: echo ${{ steps.deploy_client.outputs.url }}

